Allow user enable the '--use-fuzzy' option for the 'msgfmt' command
kellpossible/cargo-i18n pull request #68
Opened 2021-04-23 04:04 UTC by vkill

Hi @kellpossible 

Our rust project copy the .po file from iOS project. When run `cargo i18n`, the .po file like the following. So we should add `--use-fuzzy` option for `msgfmt` command.

```
#: src/main.rs:66
#, fuzzy
msgid "xxx"
msgstr "xxx"
```

Please review it. thank you.

2021-04-24 08:14 UTC, kellpossible requested changes
Hi @vkill thanks for your contribution, the pull request looks good! I only have one request that you add some documentation about the new `use_fuzzy` option to the README section about configuration https://github.com/kellpossible/cargo-i18n/blob/master/README.md#configuration

2021-04-25 01:57 UTC, vkill commented
@kellpossible I have finished, please review again.

2021-04-25 05:49 UTC, kellpossible approved these changes

2021-04-25 05:51 UTC, merged

2021-04-25 06:22 UTC, kellpossible commented
@vkill thanks for your contribution, I merged the pull request and published new versions, let me know if there's anything else I can do for you :slightly_smiling_face: